#=
Shared geometry for the "compact" (Wigner-Seitz) representation of a
periodic cell, used by both the rhombic dodecahedron (dodecahedron.jl) and
the truncated octahedron (octahedron.jl): both are literally defined as the
Wigner-Seitz cell of the lattice generated by their own `unitcell` columns
(FCC for the dodecahedron, BCC for the octahedron), and — because both
conventions deliberately use a Minkowski-reduced (shortest-vectors) basis
for that lattice — the true nearest periodic image of any point is always
among the 27 combinations of the three lattice vectors' -1/0/+1 multiples.
That search is therefore exactly the same code regardless of which shape's
`unitcell` it's given; only the `unitcell` matrix itself differs between the
two box types.
=#

#=
    _nearest_periodic_image(x::SVector{3,T}, unitcell::AbstractMatrix, center::SVector{3,T}) where {T}

Remaps `x` to the periodic image closest to `center` — the Wigner-Seitz
fundamental domain of the cell generated by `unitcell`'s columns — by brute
force over all 27 combinations of the three lattice vectors' -1/0/+1
multiples. Correct (not just a heuristic) for any Minkowski-reduced basis,
which is what both `dodecahedral_unitcell` and `octahedral_unitcell` build;
for an arbitrary/unreduced `unitcell` it's a reasonable approximation, same
caveat as any other minimum-image-convention implementation.
=#
function _nearest_periodic_image(x::SVector{3,T}, unitcell::AbstractMatrix, center::SVector{3,T}) where {T}
    rel = x - center
    v1 = SVector{3,T}(unitcell[1, 1], unitcell[2, 1], unitcell[3, 1])
    v2 = SVector{3,T}(unitcell[1, 2], unitcell[2, 2], unitcell[3, 2])
    v3 = SVector{3,T}(unitcell[1, 3], unitcell[2, 3], unitcell[3, 3])
    best = rel
    best_dist2 = sum(abs2, rel)
    for n1 in -1:1, n2 in -1:1, n3 in -1:1
        (n1 == 0 && n2 == 0 && n3 == 0) && continue
        cand = rel + n1 * v1 + n2 * v2 + n3 * v3
        dist2 = sum(abs2, cand)
        if dist2 < best_dist2
            best = cand
            best_dist2 = dist2
        end
    end
    return best + center
end
